import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FiArrowLeft, FiCheckCircle, FiKey, FiLock, FiMail } from 'react-icons/fi';
import AuthPageShell from '../components/common/AuthPageShell';
import api from '../services/api';

const ForgotPassword = () => {
  const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState('');
  const [sent, setSent] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const requestCode = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { const result = await api.post('/auth/password/forgot', { email }); setMessage(result.data.message); setSent(true); } catch (err) { setError(err.response?.data?.error || 'Unable to send a reset code.'); } finally { setLoading(false); } };
  const reset = async (event) => { event.preventDefault(); setError(''); if (password !== confirm) return setError('Passwords do not match.'); setLoading(true); try { await api.post('/auth/password/reset', { email, code, new_password: password }); setMessage('Password reset successful. Redirecting to sign in…'); setTimeout(() => navigate('/login'), 1200); } catch (err) { setError(err.response?.data?.error || 'Unable to reset password.'); } finally { setLoading(false); } };
  return <AuthPageShell><form className="auth-form" onSubmit={sent ? reset : requestCode}><div className="portal-heading__avatar mx-auto"><FiKey /></div><h1>{sent ? 'Set a new password' : 'Forgot password?'}</h1><p>{sent ? 'Enter the code sent to your email and choose a new password.' : 'We will send a secure reset code to your email.'}</p><div className="portal-rule" />{message && <div className="auth-success"><FiCheckCircle /> {message}</div>}{error && <div className="auth-error">{error}</div>}<label>Email address<div className="auth-input"><FiMail /><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="name@company.com" disabled={sent || loading} required /></div></label>{sent && <><label>6-digit verification code<div className="auth-input"><FiKey /><input inputMode="numeric" pattern="[0-9]{6}" maxLength="6" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} placeholder="000000" required /></div></label><label>New password<div className="auth-input"><FiLock /><input type="password" minLength="8" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 8 characters" required /></div></label><label>Confirm new password<div className="auth-input"><FiLock /><input type="password" minLength="8" value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Repeat your new password" required /></div></label></>}<button className="auth-submit" disabled={loading}>{loading ? 'PLEASE WAIT…' : sent ? 'RESET PASSWORD' : 'SEND RESET CODE'}</button><button type="button" className="auth-back" onClick={() => sent ? setSent(false) : navigate('/login')}><FiArrowLeft /> {sent ? 'Use a different email' : 'Back to sign in'}</button></form></AuthPageShell>;
};
export default ForgotPassword;
